## Evaluate

$ 5x^{3} - 4x^{2}y^{2} + 13xy^{2} + x^{2} -10y = out $

$ v_1 = xx $

$ v_2 = yy $

$ v_3 = 5xv_1 $

$ v_4 = 4v_1v_2 $

$ out -v_3 + v_4 - v_1 + 10y = 13xv_2 $

$ w = \begin{bmatrix}
1 & out & x & y & v_1 & v_2 & v_3 & v_4
\end{bmatrix} $



$ L = \begin{bmatrix}
1 & out & x & y & v_1 & v_2 & v_3 & v_4 \\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 5 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 4 & 0 & 0 & 0 \\
0 & 0 & 13 & 0 & 0 & 0 & 0 & 0 \\
\end{bmatrix} $


$ R = \begin{bmatrix}
1 & out & x & y & v_1 & v_2 & v_3 & v_4 \\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
\end{bmatrix} $


$ O = \begin{bmatrix}
1 & out & x & y & v_1 & v_2 & v_3 & v_4 \\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 1 & 0 & 10 & -1 & 0 & -1 & 1 \\
\end{bmatrix} $


In [71]:
import galois
import numpy as np

p = 71
# p = 21888242871839275222246405745257275088548364400416034343698204186575808495617
FP = galois.GF(p)

x = FP(2)
y = FP(3)

v1 = x * x
v2 = y * y
v3 = 5 * x * v1
v4 = 4 * v1 * v2
out = 5*x**3 - 4*x**2*y**2 + 13*x*y**2 + x**2 - 10*y

w = FP([1, out, x, y, v1, v2, v3, v4])

print("w =", w)

R = FP([[0, 0, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 0, 0],
         [0, 0, 5, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 4, 0, 0, 0],
         [0, 0, 13, 0, 0, 0, 0, 0]])

L = FP([[0, 0, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 1, 0, 0],
         [0, 0, 0, 0, 0, 1, 0, 0]])

O = FP([[0, 0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 1, 0, 0],
         [0, 0, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 0, 0, 0, 1],
         [0, 1, 0, 10, FP(p - 1), 0, FP(p - 1), 1]])

Lw = np.dot(L, w)
Rw = np.dot(R, w)
Ow = np.dot(O, w)

print("Lw =", Lw)
print("Rw =", Rw)

LwRw = np.multiply(Lw, Rw)

print("Lw * Rw =", LwRw)

print("Ow =     ", Ow)

assert np.all(LwRw == Ow)


w = [ 1 33  2  3  4  9 40  2]
Lw = [2 3 4 9 9]
Rw = [ 2  3 10 16 26]
Lw * Rw = [ 4  9 40  2 21]
Ow =      [ 4  9 40  2 21]


In [72]:
mtxs = [L, R, O]
poly_m = []

for m in mtxs:
    poly_list = []
    for i in range(0, m.shape[1]):
        points_x = FP(np.zeros(m.shape[0], dtype=int))
        points_y = FP(np.zeros(m.shape[0], dtype=int))
        for j in range(0, m.shape[0]):
            points_x[j] = FP(j+1)
            points_y[j] = m[j][i]

        poly = galois.lagrange_poly(points_x, points_y)
        coef = poly.coefficients()[::-1]
        if len(coef) < m.shape[0]:
            coef = np.append(coef, np.zeros(m.shape[0] - len(coef), dtype=int))
        poly_list.append(coef)
    
    poly_m.append(FP(poly_list))

Lp = poly_m[0]
Rp = poly_m[1]
Op = poly_m[2]

print(f'''L
{Lp}
''')

print(f'''R
{Rp}
''')

print(f'''O
{Op}
''')

L
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 5 35  0 29  3]
 [61  6  2 14 59]
 [10 16 30 68 18]
 [67 14 39 31 62]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]

R
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [68 11 24 50 61]
 [61  6  2 14 59]
 [51 17 20 31 23]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]

O
[[ 0  0  0  0  0]
 [ 1 63 34 41  3]
 [ 0  0  0  0  0]
 [10 62 56 55 30]
 [ 4 43 37 59  0]
 [61  6  2 14 59]
 [ 9 24 67 27 15]
 [67 14 39 31 62]]



In [73]:
def to_poly(mtx):
    poly_list = []
    for i in range(0, mtx.shape[0]):
        poly_list.append( galois.Poly(mtx[i][::-1]) )
    return poly_list

def print_poly(name, poly_list):
    print(f'\n{name} polynomials:')
    for i in range(0, len(poly_list)):
        print(f'{name}_{i} = {poly_list[i]}')

def evaluate_poly(poly_list, x):
    results = []
    for poly in poly_list:
        results.append(poly(x))
    return results

def print_evaluation(name, results):
    print(f'\n{name} polynomial evaluations:')
    for i in range(0, len(results)):
        print(f'{name}{i} = {results[i]}')

alpha = FP(2)
beta = FP(3)
tau = FP(20)
gamma = FP(5)
delta = FP(7)

U = to_poly(Lp)
print_poly("U", U)

V = to_poly(Rp)
print_poly("V", V)

W = to_poly(Op)
print_poly("W", W)

U_beta = [ poly * beta for poly in U ]
print_poly("βU", U_beta)

V_alpha = [ poly * alpha for poly in V ]
print_poly("αV", V_alpha)

bUaUW = np.add(np.add(U_beta, V_alpha), W)
print_poly("βU + αV + W", bUaUW)

C = evaluate_poly(bUaUW, tau)
print_evaluation("βU + αV + W", C)

T = galois.Poly(FP([1, p-1]))
for i in range(2, L.shape[0] + 1):
    T *= galois.Poly(FP([1, p-i]))

print("\nT = ", T)
for i in range(1, L.shape[0] + 2):
    print(f"T({i}) = ", T(i))
    if i == L.shape[0]:
        print("-"*10)

T_tau = T(tau)
print(f"\nT(τ) = {T_tau}")


U polynomials:
U_0 = 0
U_1 = 0
U_2 = 3x^4 + 29x^3 + 35x + 5
U_3 = 59x^4 + 14x^3 + 2x^2 + 6x + 61
U_4 = 18x^4 + 68x^3 + 30x^2 + 16x + 10
U_5 = 62x^4 + 31x^3 + 39x^2 + 14x + 67
U_6 = 0
U_7 = 0

V polynomials:
V_0 = 0
V_1 = 0
V_2 = 61x^4 + 50x^3 + 24x^2 + 11x + 68
V_3 = 59x^4 + 14x^3 + 2x^2 + 6x + 61
V_4 = 23x^4 + 31x^3 + 20x^2 + 17x + 51
V_5 = 0
V_6 = 0
V_7 = 0

W polynomials:
W_0 = 0
W_1 = 3x^4 + 41x^3 + 34x^2 + 63x + 1
W_2 = 0
W_3 = 30x^4 + 55x^3 + 56x^2 + 62x + 10
W_4 = 59x^3 + 37x^2 + 43x + 4
W_5 = 59x^4 + 14x^3 + 2x^2 + 6x + 61
W_6 = 15x^4 + 27x^3 + 67x^2 + 24x + 9
W_7 = 62x^4 + 31x^3 + 39x^2 + 14x + 67

βU polynomials:
βU_0 = 0
βU_1 = 0
βU_2 = 9x^4 + 16x^3 + 34x + 15
βU_3 = 35x^4 + 42x^3 + 6x^2 + 18x + 41
βU_4 = 54x^4 + 62x^3 + 19x^2 + 48x + 30
βU_5 = 44x^4 + 22x^3 + 46x^2 + 42x + 59
βU_6 = 0
βU_7 = 0

αV polynomials:
αV_0 = 0
αV_1 = 0
αV_2 = 51x^4 + 29x^3 + 48x^2 + 22x + 65
αV_3 = 47x^4 + 28x^3 + 4x^2 + 12x + 51
αV_4 = 46x^4 + 62x^3 + 40x^2 + 34x + 31
αV_5 = 0
αV_6 = 0
αV_7 = 0



In [74]:
from py_ecc.optimized_bn128 import multiply, G1, G2, add, pairing, neg, normalize

alpha_G1 = multiply(G1, int(alpha))
beta_G1 = multiply(G1, int(beta))
tau_G1 = [multiply(G1, int(tau**i)) for i in range(0, T.degree - 1)]
cterms_G1 = [multiply(G1, int(c)) for c in C]
t_G1 = [multiply(G1, int(tau**i * T_tau)) for i in range(0, T.degree - 2)]

beta_G2 = multiply(G2, int(beta))
tau_G2 = [multiply(G2, int(tau**i)) for i in range(0, T.degree - 1)]

In [75]:
U = galois.Poly((w @ Lp)[::-1])
V = galois.Poly((w @ Rp)[::-1])
W = galois.Poly((w @ Op)[::-1])

U_beta = galois.Poly((w @ Lp_beta)[::-1])
V_alpha = galois.Poly((w @ Rp_alpha)[::-1])

print("U = ", U)
print("V = ", V)
print("W = ", W)
print("βU = ", U_beta)
print("αV = ", V_alpha)

H = (U * V - W) // T
rem = (U * V - W) % T

print("H = ", H)
print("rem = ", rem)

assert rem == 0

U =  32x^4 + 12x^3 + 51x^2 + 65x + 55
V =  36x^4 + 53x^3 + 63x^2 + 37x + 26
W =  24x^4 + 40x^3 + 25x^2 + 57
βU =  25x^4 + 36x^3 + 11x^2 + 53x + 23
αV =  x^4 + 35x^3 + 55x^2 + 3x + 52
H =  16x^3 + 25x^2 + 24x + 14
rem =  0


u(tau) =  14
v(tau) =  22
w(tau) =  14
t(tau) =  68
h(tau) =  44


In [77]:
u = U(tau) + alpha
v = V(tau) + beta
w = W(tau)
t = T(tau)
h = H(tau)

c1 = U_beta(tau)
c2 = V_alpha(tau)

print("u(τ) = ", u)
print("v(τ) = ", v)
print("w(τ) = ", w)
print("t(τ) = ", t)
print("h(τ) = ", h)

assert u * v == alpha * beta + (w + c1 + c2) + t * h

u(τ) =  16
v(τ) =  25
w(τ) =  14
t(τ) =  68
h(τ) =  44
